=== soundpaint/serial-sniffer/src/config.xsd
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE schema [
  <!ENTITY cfg "http://www.soundpaint.org/2019/serial-sniffer/config">
]>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema"
           xmlns="&cfg;"
           targetNamespace="&cfg;"
           elementFormDefault="qualified"
           attributeFormDefault="qualified">
  <!--
  <xs:import namespace="http://www.w3.org/XML/1998/namespace"
  schemaLocation="http://www.w3.org/2001/xml.xsd" />
  -->
  <xs:element name="config" type="ConfigType" />

  <xs:complexType name="ConfigType">
    <xs:all>
      <xs:element name="devices" type="DevicesType" minOccurs="0" />
      <xs:element name="logging" type="LoggingType" minOccurs="0" />
      <xs:element name="kiosk-mode" type="KioskModeType" minOccurs="0" />
      <xs:element name="key-bindings" type="KeyBindingsType" minOccurs="0" />
      <xs:element name="audio" type="AudioType" minOccurs="0" />
    </xs:all>
  </xs:complexType>

  <xs:complexType name="DevicesType">
    <xs:all>
      <xs:element name="serial-in" type="DevPathType" minOccurs="0" />
      <xs:element name="serial-out" type="DevPathType" minOccurs="0" />
      <xs:element name="buffer-size" type="xs:nonNegativeInteger"
                  minOccurs="0" />
      <xs:element name="baud-rate" type="xs:nonNegativeInteger"
                  minOccurs="0" />
      <xs:element name="data-bits" type="xs:nonNegativeInteger"
                  minOccurs="0" />
      <xs:element name="parity-bit" type="ParityBitType" minOccurs="0" />
      <xs:element name="stop-bits" type="xs:nonNegativeInteger"
                  minOccurs="0" />
      <xs:element name="auto-start" type="xs:boolean" minOccurs="0" />
    </xs:all>
  </xs:complexType>

  <xs:complexType name="LoggingType">
    <xs:all>
      <xs:element name="enable-file-logging-on-start"
                  type="xs:boolean" minOccurs="0" />
      <xs:element name="dir-path" type="xs:string" minOccurs="0" />
      <xs:element name="filename-pattern" type="xs:string" minOccurs="0" />
      <xs:element name="append-on-start" type="xs:boolean" minOccurs="0" />
    </xs:all>
  </xs:complexType>

  <xs:complexType name="KioskModeType">
    <xs:all>
      <xs:element name="full-screen" type="xs:boolean" minOccurs="0" />
      <xs:element name="window-width"
                  type="xs:positiveInteger"
                  minOccurs="0" />
      <xs:element name="window-height"
                  type="xs:positiveInteger"
                  minOccurs="0" />
      <xs:element name="control-show-after-pressing"
                  type="xs:nonNegativeInteger"
                  minOccurs="0" />
      <xs:element name="control-autohide-after"
                  type="xs:nonNegativeInteger"
                  minOccurs="0" />
      <xs:element name="enable-cursor" type="xs:boolean" minOccurs="0" />
      <xs:element name="enable-button-quit" type="xs:boolean" minOccurs="0" />
    </xs:all>
  </xs:complexType>

  <xs:complexType name="KeyBindingsType">
    <xs:sequence>
      <xs:element name="action" type="ActionType"
                  minOccurs="0" maxOccurs="unbounded" />
    </xs:sequence>
  </xs:complexType>

  <xs:complexType name="ActionType">
    <xs:all>
      <xs:element name="id" type="ActionIdType" minOccurs="1" />
      <xs:element name="keys" type="KeysType" minOccurs="1" />
    </xs:all>
  </xs:complexType>

  <xs:simpleType name="ActionIdType">
    <xs:restriction base="xs:string">
      <xs:enumeration value="Menu" />
      <xs:enumeration value="Quit" />
      <xs:enumeration value="About" />
      <xs:enumeration value="License" />
      <xs:enumeration value="Audio_decrement_volume" />
      <xs:enumeration value="Audio_increment_volume" />
      <xs:enumeration value="Audio_mute_unmute" />
    </xs:restriction>
  </xs:simpleType>

  <xs:complexType name="KeysType">
    <xs:sequence>
      <xs:element name="key" type="HexIntType"
                  minOccurs="0" maxOccurs="unbounded" />
    </xs:sequence>
  </xs:complexType>

  <xs:complexType name="AudioType">
    <xs:all>
      <xs:element name="enable-audio" type="xs:boolean" minOccurs="0" />
      <xs:element name="enable-volume-control" type="xs:boolean"
                  minOccurs="0" />
      <xs:element name="sample-scale" type="xs:float" minOccurs="0" />
      <xs:element name="sample-rate" type="xs:positiveInteger" minOccurs="0" />
      <xs:element name="channels" type="xs:positiveInteger" minOccurs="0" />
      <xs:element name="alsa-verbose" type="xs:boolean" minOccurs="0" />
      <xs:element name="alsa-playback-device" type="xs:string" minOccurs="0" />
      <xs:element name="alsa-buffer-time" type="xs:positiveInteger"
                  minOccurs="0" />
      <xs:element name="alsa-period-time" type="xs:positiveInteger"
                  minOccurs="0" />
      <xs:element name="initial-volume" type="UnitFractionType"
                  minOccurs="0" />
    </xs:all>
  </xs:complexType>

  <xs:complexType name="DevPathType">
    <xs:all>
      <xs:element name="path" type="xs:string" minOccurs="0" />
    </xs:all>
  </xs:complexType>

  <xs:simpleType name="ParityBitType">
    <xs:restriction base="xs:string">
      <xs:enumeration value="none" />
      <xs:enumeration value="even" />
      <xs:enumeration value="odd" />
    </xs:restriction>
  </xs:simpleType>

  <xs:simpleType name="HexIntType">
    <xs:restriction base="xs:string">
      <xs:pattern value="0[Xx][A-Fa-f0-9]{1,8}"/>
    </xs:restriction>
  </xs:simpleType>

  <xs:simpleType name="NonNegativeDoubleType">
    <xs:restriction base="xs:double">
      <xs:minInclusive value="0.0"/>
    </xs:restriction>
  </xs:simpleType>

  <xs:simpleType name="UnitFractionType">
    <xs:restriction base="NonNegativeDoubleType">
      <xs:maxInclusive value="1.0"/>
    </xs:restriction>
  </xs:simpleType>
</xs:schema>

<!--
    Local Variables:
      coding:utf-8
      mode:xml
    End:
-->

=== soundpaint/serial-sniffer/src/config.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE config [
  <!ENTITY cfg "http://www.soundpaint.org/2019/serial-sniffer/config">
]>

<config
    xmlns="&cfg;"
    xmlns:cfg="&cfg;"
    xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xsi:schemaLocation="&cfg; config.xsd">
  <devices>
    <!-- file path of serial input device -->
    <serial-in>
      <path>/dev/ttyS0</path>
    </serial-in>

    <!-- file path of serial output device -->
    <serial-out>
      <path>/dev/ttyS1</path>
    </serial-out>

    <!-- buffer size -->
    <buffer-size>16</buffer-size>

    <!-- baud rate -->
    <baud-rate>9600</baud-rate>

    <!-- number data bits, either 7 or 8 -->
    <data-bits>8</data-bits>

    <!-- parity bit, one of "none", "even", "odd" -->
    <parity-bit>none</parity-bit>

    <!-- number stop bits, either 1 or 2 -->
    <stop-bits>2</stop-bits>

    <!-- automatically start serial data streams on application start? -->
    <auto-start>false</auto-start>
  </devices>
  <logging>
    <!-- enable / disable logging to file(s) on start -->
    <enable-file-logging-on-start>true</enable-file-logging-on-start>

    <!-- logging directory path -->
    <dir-path>.</dir-path>

    <!-- log filename pattern

         supported pattern variables:
         * $DATE$: will be replaced with current date and time

         * $UID$: will be replace with ID that is unique among all log
           files in the selected logging directory

         Use "$$" as escape symbol for "$".
    -->
    <filename-pattern>serial-sniffer_$DATE$_$UID$.log</filename-pattern>

    <!-- enable / disable appending on start to existing log file -->
    <append-on-start>true</append-on-start>
  </logging>
  <kiosk-mode>
    <!-- start application in a window or full screen? -->
    <full-screen>false</full-screen>

    <!-- if application is started in a window, use this window width
         [px] -->
    <window-width>800</window-width>

    <!-- if application is started in a window, use this window height
         [px] -->
    <window-height>640</window-height>

    <!-- show the control window after touching the screen the
         specfied amount of seconds.  If set to 0, the control window
         will never show this way -->
    <control-show-after-pressing>0</control-show-after-pressing>

    <!-- hide the control window after the specfied amount of
         seconds.  If set to 0, the control window will never hide -->
    <control-autohide-after>4</control-autohide-after>

    <!-- enable / disable the X Window System or Wayland cursor -->
    <enable-cursor>true</enable-cursor>

    <!-- enable / disable display of "quit" button -->
    <enable-button-quit>true</enable-button-quit>
  </kiosk-mode>
  <key-bindings>
    <!--
        NOTE: Some special keys like Qt::Space, Qt::Key_Left and
        Qt::Key_Right may already be caught by the window manager for
        window actions like browsing through the GUI.  If this is the
        case, defining bindings for such keys in this section will
        show no effect.  In doubt, for checking, replace it with a
        regular key, like any of the 26 letter keys.
    -->
    <action>
      <id>Menu</id>
      <keys>
        <key>0x01000055</key> <!-- Qt::Key_Menu -->
        <key>0x010000dc</key> <!-- Qt::Key_MenuKB -->
        <key>0x01000030</key> <!-- Qt::Key_F1 -->
        <key>0x0000003f</key> <!-- Qt::Key_Question -->
        <key>0x00000023</key> <!-- Qt::Key_NumberSign -->
      </keys>
    </action>
    <action>
      <id>Quit</id>
      <keys>
        <key>0x00000051</key> <!-- Qt::Key_Q -->
        <key>0x01000000</key> <!-- Qt::Key_Escape -->
        <key>0x010000b7</key> <!-- Qt::Key_PowerOff -->
        <key>0x0102000a</key> <!-- Qt::Key_Exit -->
      </keys>
    </action>
    <action>
      <id>About</id>
      <keys>
        <key>0x00000041</key> <!-- Qt::Key_A -->
        <key>0x0100011b</key> <!-- Qt::Key_Info -->
      </keys>
    </action>
    <action>
      <id>License</id>
      <keys>
        <key>0x00000043</key> <!-- Qt::Key_C -->
      </keys>
    </action>
    <action>
      <id>Audio_decrement_volume</id>
      <keys>
        <key>0x0000002d</key> <!-- Qt::Key_Minus -->
        <key>0x01000070</key> <!-- Qt::Key_VolumeDown -->
      </keys>
    </action>
    <action>
      <id>Audio_increment_volume</id>
      <keys>
        <key>0x0000002b</key> <!-- Qt::Key_Plus -->
        <key>0x01000072</key> <!-- Qt::Key_VolumeUp -->
      </keys>
    </action>
    <action>
      <id>Audio_mute_unmute</id>
      <keys>
        <key>0x0000004d</key> <!-- Qt::Key_M -->
        <key>0x01000071</key> <!-- Qt::Key_VolumeMute -->
      </keys>
    </action>
  </key-bindings>
  <audio>
    <!-- enable / disable audio -->
    <enable-audio>true</enable-audio>

    <!-- enable / disable volume control -->
    <enable-volume-control>true</enable-volume-control>

    <!-- global volume correction; should be usually 1.0 -->
    <sample-scale>1</sample-scale>

    <!-- samples per second, usually 44100 -->
    <sample-rate>44100</sample-rate>

    <!-- for ordinary stereo, choose 2 channels -->
    <channels>2</channels>

    <!-- if "true", be more verbose on ALSA specific operations -->
    <alsa-verbose>true</alsa-verbose>

    <!-- if "default" does not work, try "plughw:0,0" instead -->
    <alsa-playback-device>default</alsa-playback-device>

    <!-- size of audio buffer in [µs] -->
    <alsa-buffer-time>250000</alsa-buffer-time>

    <!-- period time in [µs] -->
    <alsa-period-time>50000</alsa-period-time>

    <!-- minimum volume is 0.0, maximum volume is 1.0 -->
    <initial-volume>0.8</initial-volume>
  </audio>

</config>

<!--
    Local Variables:
      coding:utf-8
      mode:xml
    End:
-->
